# This file was automagically generated by mbed.org. For more information, 
# see http://mbed.org/handbook/Exporting-to-GCC-ARM-Embedded

###############################################################################
# Boiler-plate

# cross-platform directory manipulation
ifeq ($(shell echo $$OS),$$OS)
    MAKEDIR = if not exist "$(1)" mkdir "$(1)"
    RM = rmdir /S /Q "$(1)"
else
    MAKEDIR = '$(SHELL)' -c "mkdir -p \"$(1)\""
    RM = '$(SHELL)' -c "rm -rf \"$(1)\""
endif

OBJDIR := BUILD
# Move to the build directory
ifeq (,$(filter $(OBJDIR),$(notdir $(CURDIR))))
.SUFFIXES:
mkfile_path := $(abspath $(lastword $(MAKEFILE_LIST)))
MAKETARGET = '$(MAKE)' --no-print-directory -C $(OBJDIR) -f '$(mkfile_path)' \
		'SRCDIR=$(CURDIR)' $(MAKECMDGOALS)
.PHONY: $(OBJDIR) clean
all:
	+@$(call MAKEDIR,$(OBJDIR))
	+@$(MAKETARGET)
$(OBJDIR): all
Makefile : ;
% :: $(OBJDIR) ; :
clean :
	$(call RM,$(OBJDIR))

else

# trick rules into thinking we are in the root, when we are in the bulid dir
VPATH = ..

# Boiler-plate
###############################################################################
# Project settings

PROJECT := servoController


# Project settings
###############################################################################
# Objects and Paths

OBJECTS += ../../custom_targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE/TARGET_WEACT_F411CE/PeripheralPins.o
OBJECTS += ../../custom_targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE/TARGET_WEACT_F411CE/system_clock.o
OBJECTS += ../../libs/Adafruit-GFX-Library/Adafruit_GFX.o
OBJECTS += ../../libs/Adafruit-GFX-Library/Adafruit_SPITFT.o
OBJECTS += ../../libs/Adafruit-GFX-Library/glcdfont.o
OBJECTS += ../../libs/Adafruit_ADS1015/Adafruit_ADS1015.o
OBJECTS += ../../libs/Adafruit_ST7735/Adafruit_ST7735.o
OBJECTS += ../../libs/Chart/Chart.o
OBJECTS += ../../libs/Chart/DataBuffer.o
OBJECTS += ../../libs/Chart/DataRecorder.o
OBJECTS += ../../libs/Chart/GfxItem.o
OBJECTS += ../../libs/Chart/GraphBase.o
OBJECTS += ../../libs/Chart/Grid.o
OBJECTS += ../../libs/Chart/LineGraph.o
OBJECTS += ../../libs/Chart/PlotArea.o
OBJECTS += ../../libs/Chart/Scale.o
OBJECTS += ../../libs/DHT/DHT.o
OBJECTS += ../../libs/IRSensorD6T/IRSensorD6T.o
OBJECTS += ../../libs/Interfaces/FSMC.o
OBJECTS += ../../libs/MCP23017/MCP23017.o
OBJECTS += ../../libs/MD_MAX72XX/src/MD_MAX72xx.o
OBJECTS += ../../libs/MD_MAX72XX/src/MD_MAX72xx_buf.o
OBJECTS += ../../libs/MD_MAX72XX/src/MD_MAX72xx_font.o
OBJECTS += ../../libs/MD_MAX72XX/src/MD_MAX72xx_pix.o
OBJECTS += ../../libs/MD_Parola/src/MD_PZone.o
OBJECTS += ../../libs/MD_Parola/src/MD_Parola.o
OBJECTS += ../../libs/MD_Parola/src/MD_Parola_Blinds.o
OBJECTS += ../../libs/MD_Parola/src/MD_Parola_Close.o
OBJECTS += ../../libs/MD_Parola/src/MD_Parola_Diag.o
OBJECTS += ../../libs/MD_Parola/src/MD_Parola_Dissolve.o
OBJECTS += ../../libs/MD_Parola/src/MD_Parola_Fade.o
OBJECTS += ../../libs/MD_Parola/src/MD_Parola_Grow.o
OBJECTS += ../../libs/MD_Parola/src/MD_Parola_HScroll.o
OBJECTS += ../../libs/MD_Parola/src/MD_Parola_Mesh.o
OBJECTS += ../../libs/MD_Parola/src/MD_Parola_Open.o
OBJECTS += ../../libs/MD_Parola/src/MD_Parola_Print.o
OBJECTS += ../../libs/MD_Parola/src/MD_Parola_Random.o
OBJECTS += ../../libs/MD_Parola/src/MD_Parola_Scan.o
OBJECTS += ../../libs/MD_Parola/src/MD_Parola_Slice.o
OBJECTS += ../../libs/MD_Parola/src/MD_Parola_Sprite.o
OBJECTS += ../../libs/MD_Parola/src/MD_Parola_VScroll.o
OBJECTS += ../../libs/MD_Parola/src/MD_Parola_Wipe.o
OBJECTS += ../../libs/MQTTPacket/MQTTConnectClient.o
OBJECTS += ../../libs/MQTTPacket/MQTTConnectServer.o
OBJECTS += ../../libs/MQTTPacket/MQTTDeserializePublish.o
OBJECTS += ../../libs/MQTTPacket/MQTTFormat.o
OBJECTS += ../../libs/MQTTPacket/MQTTPacket.o
OBJECTS += ../../libs/MQTTPacket/MQTTSerializePublish.o
OBJECTS += ../../libs/MQTTPacket/MQTTSubscribeClient.o
OBJECTS += ../../libs/MQTTPacket/MQTTSubscribeServer.o
OBJECTS += ../../libs/MQTTPacket/MQTTUnsubscribeClient.o
OBJECTS += ../../libs/MQTTPacket/MQTTUnsubscribeServer.o
OBJECTS += ../../libs/Math/PID.o
OBJECTS += ../../libs/OneButton/OneButton.o
OBJECTS += ../../libs/Radio/RFM69.o
OBJECTS += ../../libs/Radio/rfm12.o
OBJECTS += ../../libs/Sensors/MAX31865.o
OBJECTS += ../../libs/Sensors/RTDAnalog.o
OBJECTS += ../../libs/Sensors/Sht31.o
OBJECTS += ../../libs/Sensors/VL6180.o
OBJECTS += ../../libs/Sensors/i2c.o
OBJECTS += ../../libs/Sensors/sht15.o
OBJECTS += ../../libs/TextLCD/TextLCD.o
OBJECTS += ../../libs/util/Json.o
OBJECTS += ../../libs/util/StopWatch.o
OBJECTS += ../../libs/util/TARGET_STM32F4/HWTimer.o
OBJECTS += ../../libs/util/cmdb.o
OBJECTS += ../../libs/util/dconfig.o
OBJECTS += ../../libs/util/jsmn.o
OBJECTS += ../../libs/util/statistics.o
OBJECTS += ../../libs/util/stepper.o
OBJECTS += ../../mbed-os/cmsis/TARGET_CORTEX_M/mbed_tz_context.o
OBJECTS += ../../mbed-os/components/storage/blockdevice/COMPONENT_SPIF/SPIFBlockDevice.o
OBJECTS += ../../mbed-os/drivers/source/AnalogIn.o
OBJECTS += ../../mbed-os/drivers/source/AnalogOut.o
OBJECTS += ../../mbed-os/drivers/source/BufferedSerial.o
OBJECTS += ../../mbed-os/drivers/source/BusIn.o
OBJECTS += ../../mbed-os/drivers/source/BusInOut.o
OBJECTS += ../../mbed-os/drivers/source/BusOut.o
OBJECTS += ../../mbed-os/drivers/source/CAN.o
OBJECTS += ../../mbed-os/drivers/source/DigitalIn.o
OBJECTS += ../../mbed-os/drivers/source/DigitalInOut.o
OBJECTS += ../../mbed-os/drivers/source/DigitalOut.o
OBJECTS += ../../mbed-os/drivers/source/FlashIAP.o
OBJECTS += ../../mbed-os/drivers/source/I2C.o
OBJECTS += ../../mbed-os/drivers/source/I2CSlave.o
OBJECTS += ../../mbed-os/drivers/source/InterruptIn.o
OBJECTS += ../../mbed-os/drivers/source/MbedCRC.o
OBJECTS += ../../mbed-os/drivers/source/PortIn.o
OBJECTS += ../../mbed-os/drivers/source/PortInOut.o
OBJECTS += ../../mbed-os/drivers/source/PortOut.o
OBJECTS += ../../mbed-os/drivers/source/PwmOut.o
OBJECTS += ../../mbed-os/drivers/source/QSPI.o
OBJECTS += ../../mbed-os/drivers/source/ResetReason.o
OBJECTS += ../../mbed-os/drivers/source/SFDP.o
OBJECTS += ../../mbed-os/drivers/source/SPI.o
OBJECTS += ../../mbed-os/drivers/source/SPISlave.o
OBJECTS += ../../mbed-os/drivers/source/SerialBase.o
OBJECTS += ../../mbed-os/drivers/source/SerialWireOutput.o
OBJECTS += ../../mbed-os/drivers/source/Ticker.o
OBJECTS += ../../mbed-os/drivers/source/Timeout.o
OBJECTS += ../../mbed-os/drivers/source/Timer.o
OBJECTS += ../../mbed-os/drivers/source/TimerEvent.o
OBJECTS += ../../mbed-os/drivers/source/UnbufferedSerial.o
OBJECTS += ../../mbed-os/drivers/source/Watchdog.o
OBJECTS += ../../mbed-os/events/source/EventQueue.o
OBJECTS += ../../mbed-os/events/source/equeue.o
OBJECTS += ../../mbed-os/events/source/equeue_mbed.o
OBJECTS += ../../mbed-os/events/source/equeue_posix.o
OBJECTS += ../../mbed-os/events/source/mbed_shared_queues.o
OBJECTS += ../../mbed-os/features/frameworks/mbed-trace/source/mbed_trace.o
OBJECTS += ../../mbed-os/features/storage/blockdevice/BufferedBlockDevice.o
OBJECTS += ../../mbed-os/features/storage/blockdevice/ChainingBlockDevice.o
OBJECTS += ../../mbed-os/features/storage/blockdevice/ExhaustibleBlockDevice.o
OBJECTS += ../../mbed-os/features/storage/blockdevice/FlashSimBlockDevice.o
OBJECTS += ../../mbed-os/features/storage/blockdevice/HeapBlockDevice.o
OBJECTS += ../../mbed-os/features/storage/blockdevice/MBRBlockDevice.o
OBJECTS += ../../mbed-os/features/storage/blockdevice/ObservingBlockDevice.o
OBJECTS += ../../mbed-os/features/storage/blockdevice/ProfilingBlockDevice.o
OBJECTS += ../../mbed-os/features/storage/blockdevice/ReadOnlyBlockDevice.o
OBJECTS += ../../mbed-os/features/storage/blockdevice/SlicingBlockDevice.o
OBJECTS += ../../mbed-os/features/storage/filesystem/Dir.o
OBJECTS += ../../mbed-os/features/storage/filesystem/File.o
OBJECTS += ../../mbed-os/features/storage/filesystem/FileSystem.o
OBJECTS += ../../mbed-os/features/storage/filesystem/fat/ChaN/ff.o
OBJECTS += ../../mbed-os/features/storage/filesystem/fat/ChaN/ffunicode.o
OBJECTS += ../../mbed-os/features/storage/filesystem/fat/FATFileSystem.o
OBJECTS += ../../mbed-os/features/storage/filesystem/littlefsv2/LittleFileSystem2.o
OBJECTS += ../../mbed-os/features/storage/filesystem/littlefsv2/littlefs/lfs2.o
OBJECTS += ../../mbed-os/features/storage/filesystem/littlefsv2/littlefs/lfs2_util.o
OBJECTS += ../../mbed-os/hal/LowPowerTickerWrapper.o
OBJECTS += ../../mbed-os/hal/mbed_compat.o
OBJECTS += ../../mbed-os/hal/mbed_critical_section_api.o
OBJECTS += ../../mbed-os/hal/mbed_flash_api.o
OBJECTS += ../../mbed-os/hal/mbed_gpio.o
OBJECTS += ../../mbed-os/hal/mbed_gpio_irq.o
OBJECTS += ../../mbed-os/hal/mbed_itm_api.o
OBJECTS += ../../mbed-os/hal/mbed_lp_ticker_api.o
OBJECTS += ../../mbed-os/hal/mbed_lp_ticker_wrapper.o
OBJECTS += ../../mbed-os/hal/mbed_pinmap_common.o
OBJECTS += ../../mbed-os/hal/mbed_pinmap_default.o
OBJECTS += ../../mbed-os/hal/mbed_ticker_api.o
OBJECTS += ../../mbed-os/hal/mbed_us_ticker_api.o
OBJECTS += ../../mbed-os/hal/mpu/mbed_mpu_v7m.o
OBJECTS += ../../mbed-os/hal/mpu/mbed_mpu_v8m.o
OBJECTS += ../../mbed-os/hal/static_pinmap.o
OBJECTS += ../../mbed-os/hal/usb/mbed_usb_phy.o
OBJECTS += ../../mbed-os/platform/cxxsupport/mstd_mutex.o
OBJECTS += ../../mbed-os/platform/source/ATCmdParser.o
OBJECTS += ../../mbed-os/platform/source/CThunkBase.o
OBJECTS += ../../mbed-os/platform/source/CriticalSectionLock.o
OBJECTS += ../../mbed-os/platform/source/DeepSleepLock.o
OBJECTS += ../../mbed-os/platform/source/FileBase.o
OBJECTS += ../../mbed-os/platform/source/FileHandle.o
OBJECTS += ../../mbed-os/platform/source/FilePath.o
OBJECTS += ../../mbed-os/platform/source/FileSystemHandle.o
OBJECTS += ../../mbed-os/platform/source/LocalFileSystem.o
OBJECTS += ../../mbed-os/platform/source/Stream.o
OBJECTS += ../../mbed-os/platform/source/SysTimer.o
OBJECTS += ../../mbed-os/platform/source/TARGET_CORTEX_M/TOOLCHAIN_GCC/except.o
OBJECTS += ../../mbed-os/platform/source/TARGET_CORTEX_M/mbed_fault_handler.o
OBJECTS += ../../mbed-os/platform/source/mbed_alloc_wrappers.o
OBJECTS += ../../mbed-os/platform/source/mbed_application.o
OBJECTS += ../../mbed-os/platform/source/mbed_assert.o
OBJECTS += ../../mbed-os/platform/source/mbed_atomic_impl.o
OBJECTS += ../../mbed-os/platform/source/mbed_board.o
OBJECTS += ../../mbed-os/platform/source/mbed_critical.o
OBJECTS += ../../mbed-os/platform/source/mbed_error.o
OBJECTS += ../../mbed-os/platform/source/mbed_error_hist.o
OBJECTS += ../../mbed-os/platform/source/mbed_interface.o
OBJECTS += ../../mbed-os/platform/source/mbed_mem_trace.o
OBJECTS += ../../mbed-os/platform/source/mbed_mktime.o
OBJECTS += ../../mbed-os/platform/source/mbed_mpu_mgmt.o
OBJECTS += ../../mbed-os/platform/source/mbed_os_timer.o
OBJECTS += ../../mbed-os/platform/source/mbed_poll.o
OBJECTS += ../../mbed-os/platform/source/mbed_power_mgmt.o
OBJECTS += ../../mbed-os/platform/source/mbed_retarget.o
OBJECTS += ../../mbed-os/platform/source/mbed_rtc_time.o
OBJECTS += ../../mbed-os/platform/source/mbed_sdk_boot.o
OBJECTS += ../../mbed-os/platform/source/mbed_semihost_api.o
OBJECTS += ../../mbed-os/platform/source/mbed_stats.o
OBJECTS += ../../mbed-os/platform/source/mbed_thread.o
OBJECTS += ../../mbed-os/platform/source/mbed_wait_api_no_rtos.o
OBJECTS += ../../mbed-os/platform/source/minimal-printf/mbed_printf_armlink_overrides.o
OBJECTS += ../../mbed-os/platform/source/minimal-printf/mbed_printf_implementation.o
OBJECTS += ../../mbed-os/platform/source/minimal-printf/mbed_printf_wrapper.o
OBJECTS += ../../mbed-os/rtos/source/ConditionVariable.o
OBJECTS += ../../mbed-os/rtos/source/EventFlags.o
OBJECTS += ../../mbed-os/rtos/source/Kernel.o
OBJECTS += ../../mbed-os/rtos/source/Mutex.o
OBJECTS += ../../mbed-os/rtos/source/Semaphore.o
OBJECTS += ../../mbed-os/rtos/source/ThisThread.o
OBJECTS += ../../mbed-os/rtos/source/Thread.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/Legacy/stm32f4xx_hal_can_legacy.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_adc.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_adc_ex.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_can.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_cec.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_cortex.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_crc.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_cryp.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_cryp_ex.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_dac.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_dac_ex.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_dcmi.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_dcmi_ex.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_dfsdm.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_dma.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_dma2d.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_dma_ex.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_dsi.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_eth.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_exti.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_flash.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_flash_ex.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_flash_ramfunc.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_fmpi2c.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_fmpi2c_ex.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_fmpsmbus.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_gpio.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_hash.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_hash_ex.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_hcd.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_i2c.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_i2c_ex.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_i2s.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_i2s_ex.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_irda.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_iwdg.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_lptim.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_ltdc.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_ltdc_ex.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_mmc.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_nand.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_nor.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_pccard.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_pcd.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_pcd_ex.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_pwr.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_pwr_ex.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_qspi.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_rcc.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_rcc_ex.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_rng.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_rtc.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_rtc_ex.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_sai.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_sai_ex.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_sd.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_sdram.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_smartcard.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_smbus.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_spdifrx.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_spi.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_sram.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_tim.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_tim_ex.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_uart.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_usart.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_wwdg.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_ll_adc.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_ll_crc.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_ll_dac.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_ll_dma.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_ll_dma2d.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_ll_exti.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_ll_fmc.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_ll_fmpi2c.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_ll_fsmc.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_ll_gpio.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_ll_i2c.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_ll_lptim.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_ll_pwr.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_ll_rcc.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_ll_rng.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_ll_rtc.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_ll_sdmmc.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_ll_spi.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_ll_tim.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_ll_usart.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_ll_usb.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_ll_utils.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/system_stm32f4xx.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE/TOOLCHAIN_GCC_ARM/startup_stm32f411xe.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/analogin_device.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/analogout_device.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/flash_api.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/gpio_irq_device.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/pwmout_device.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/serial_device.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/spi_api.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/USBPhy_STM32.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/analogin_api.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/analogout_api.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/can_api.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/gpio_api.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/gpio_irq_api.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/hal_tick_overrides.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/i2c_api.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/lp_ticker.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/mbed_crc_api.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/mbed_overrides.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/pinmap.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/port_api.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/pwmout_api.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/qspi_api.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/reset_reason.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/rtc_api.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/serial_api.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/sleep.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/stm_spi_api.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/trng_api.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/us_ticker.o
OBJECTS += ../../mbed-os/targets/TARGET_STM/watchdog_api.o
OBJECTS += ./source/MainConfig.o
OBJECTS += ./source/Test_Parola.o
OBJECTS += ./source/console.o
OBJECTS += ./source/globals.o
OBJECTS += ./source/main.o
OBJECTS += ./source/util.o


INCLUDE_PATHS += -I../.
INCLUDE_PATHS += -I../../../custom_targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE/TARGET_WEACT_F411CE
INCLUDE_PATHS += -I../../../libs
INCLUDE_PATHS += -I../../../libs/Adafruit-GFX-Library
INCLUDE_PATHS += -I../../../libs/Adafruit-GFX-Library/Fonts
INCLUDE_PATHS += -I../../../libs/Adafruit_ADS1015
INCLUDE_PATHS += -I../../../libs/Adafruit_ST7735
INCLUDE_PATHS += -I../../../libs/Chart
INCLUDE_PATHS += -I../../../libs/DHT
INCLUDE_PATHS += -I../../../libs/IRSensorD6T
INCLUDE_PATHS += -I../../../libs/Interfaces
INCLUDE_PATHS += -I../../../libs/MCP23017
INCLUDE_PATHS += -I../../../libs/MD_MAX72XX
INCLUDE_PATHS += -I../../../libs/MD_MAX72XX/src
INCLUDE_PATHS += -I../../../libs/MD_Parola
INCLUDE_PATHS += -I../../../libs/MD_Parola/src
INCLUDE_PATHS += -I../../../libs/MQTTPacket
INCLUDE_PATHS += -I../../../libs/Math
INCLUDE_PATHS += -I../../../libs/OneButton
INCLUDE_PATHS += -I../../../libs/Radio
INCLUDE_PATHS += -I../../../libs/Sensors
INCLUDE_PATHS += -I../../../libs/TextLCD
INCLUDE_PATHS += -I../../../libs/util
INCLUDE_PATHS += -I../../../mbed-os
INCLUDE_PATHS += -I../../../mbed-os/cmsis
INCLUDE_PATHS += -I../../../mbed-os/cmsis/TARGET_CORTEX_M
INCLUDE_PATHS += -I../../../mbed-os/components
INCLUDE_PATHS += -I../../../mbed-os/components/802.15.4_RF
INCLUDE_PATHS += -I../../../mbed-os/components/802.15.4_RF/atmel-rf-driver
INCLUDE_PATHS += -I../../../mbed-os/components/802.15.4_RF/mcr20a-rf-driver
INCLUDE_PATHS += -I../../../mbed-os/components/802.15.4_RF/stm-s2lp-rf-driver
INCLUDE_PATHS += -I../../../mbed-os/components/storage/blockdevice/COMPONENT_FLASHIAP
INCLUDE_PATHS += -I../../../mbed-os/components/storage/blockdevice/COMPONENT_SPIF
INCLUDE_PATHS += -I../../../mbed-os/components/wifi
INCLUDE_PATHS += -I../../../mbed-os/components/wifi/esp8266-driver
INCLUDE_PATHS += -I../../../mbed-os/drivers
INCLUDE_PATHS += -I../../../mbed-os/drivers/internal
INCLUDE_PATHS += -I../../../mbed-os/events
INCLUDE_PATHS += -I../../../mbed-os/events/internal
INCLUDE_PATHS += -I../../../mbed-os/features
INCLUDE_PATHS += -I../../../mbed-os/features/cellular
INCLUDE_PATHS += -I../../../mbed-os/features/device_key
INCLUDE_PATHS += -I../../../mbed-os/features/frameworks
INCLUDE_PATHS += -I../../../mbed-os/features/frameworks/greentea-client
INCLUDE_PATHS += -I../../../mbed-os/features/frameworks/mbed-client-cli
INCLUDE_PATHS += -I../../../mbed-os/features/frameworks/mbed-client-randlib
INCLUDE_PATHS += -I../../../mbed-os/features/frameworks/mbed-coap
INCLUDE_PATHS += -I../../../mbed-os/features/frameworks/mbed-trace
INCLUDE_PATHS += -I../../../mbed-os/features/frameworks/mbed-trace/mbed-trace
INCLUDE_PATHS += -I../../../mbed-os/features/frameworks/nanostack-libservice
INCLUDE_PATHS += -I../../../mbed-os/features/frameworks/unity
INCLUDE_PATHS += -I../../../mbed-os/features/frameworks/utest
INCLUDE_PATHS += -I../../../mbed-os/features/lorawan
INCLUDE_PATHS += -I../../../mbed-os/features/lwipstack
INCLUDE_PATHS += -I../../../mbed-os/features/mbedtls
INCLUDE_PATHS += -I../../../mbed-os/features/nanostack
INCLUDE_PATHS += -I../../../mbed-os/features/nanostack/coap-service
INCLUDE_PATHS += -I../../../mbed-os/features/nanostack/mbed-mesh-api
INCLUDE_PATHS += -I../../../mbed-os/features/nanostack/nanostack-hal-mbed-cmsis-rtos
INCLUDE_PATHS += -I../../../mbed-os/features/nanostack/nanostack-interface
INCLUDE_PATHS += -I../../../mbed-os/features/nanostack/sal-stack-nanostack
INCLUDE_PATHS += -I../../../mbed-os/features/nanostack/sal-stack-nanostack-eventloop
INCLUDE_PATHS += -I../../../mbed-os/features/netsocket
INCLUDE_PATHS += -I../../../mbed-os/features/storage
INCLUDE_PATHS += -I../../../mbed-os/features/storage/blockdevice
INCLUDE_PATHS += -I../../../mbed-os/features/storage/filesystem
INCLUDE_PATHS += -I../../../mbed-os/features/storage/filesystem/fat
INCLUDE_PATHS += -I../../../mbed-os/features/storage/filesystem/fat/ChaN
INCLUDE_PATHS += -I../../../mbed-os/features/storage/filesystem/littlefs
INCLUDE_PATHS += -I../../../mbed-os/features/storage/filesystem/littlefsv2
INCLUDE_PATHS += -I../../../mbed-os/features/storage/filesystem/littlefsv2/littlefs
INCLUDE_PATHS += -I../../../mbed-os/features/storage/kvstore
INCLUDE_PATHS += -I../../../mbed-os/features/storage/kvstore/conf
INCLUDE_PATHS += -I../../../mbed-os/features/storage/kvstore/direct_access_devicekey
INCLUDE_PATHS += -I../../../mbed-os/features/storage/kvstore/filesystemstore
INCLUDE_PATHS += -I../../../mbed-os/features/storage/kvstore/global_api
INCLUDE_PATHS += -I../../../mbed-os/features/storage/kvstore/include
INCLUDE_PATHS += -I../../../mbed-os/features/storage/kvstore/kv_map
INCLUDE_PATHS += -I../../../mbed-os/features/storage/kvstore/securestore
INCLUDE_PATHS += -I../../../mbed-os/features/storage/kvstore/tdbstore
INCLUDE_PATHS += -I../../../mbed-os/hal
INCLUDE_PATHS += -I../../../mbed-os/hal/usb
INCLUDE_PATHS += -I../../../mbed-os/platform
INCLUDE_PATHS += -I../../../mbed-os/platform/cxxsupport
INCLUDE_PATHS += -I../../../mbed-os/platform/internal
INCLUDE_PATHS += -I../../../mbed-os/platform/source
INCLUDE_PATHS += -I../../../mbed-os/platform/source/minimal-printf
INCLUDE_PATHS += -I../../../mbed-os/rtos
INCLUDE_PATHS += -I../../../mbed-os/rtos/source
INCLUDE_PATHS += -I../../../mbed-os/rtos/source/TARGET_CORTEX
INCLUDE_PATHS += -I../../../mbed-os/targets/TARGET_STM
INCLUDE_PATHS += -I../../../mbed-os/targets/TARGET_STM/TARGET_STM32F4
INCLUDE_PATHS += -I../../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW
INCLUDE_PATHS += -I../../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/CMSIS
INCLUDE_PATHS += -I../../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver
INCLUDE_PATHS += -I../../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/Legacy
INCLUDE_PATHS += -I../../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE
INCLUDE_PATHS += -I.././source
INCLUDE_PATHS += -I../D:/Projects/Sn/LocalGit/Mbed5-Projects/mbed-os

LIBRARY_PATHS :=
LIBRARIES :=
LINKER_SCRIPT ?= ../../../mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE/TOOLCHAIN_GCC_ARM/STM32F411XE.ld

# Objects and Paths
###############################################################################
# Tools and Flags

AS      = arm-none-eabi-gcc
CC      = arm-none-eabi-gcc
CPP     = arm-none-eabi-g++
LD      = arm-none-eabi-gcc
ELF2BIN = arm-none-eabi-objcopy
PREPROC = arm-none-eabi-cpp -E -P -Wl,--gc-sections -Wl,--wrap,main -Wl,--wrap,_malloc_r -Wl,--wrap,_free_r -Wl,--wrap,_realloc_r -Wl,--wrap,_memalign_r -Wl,--wrap,_calloc_r -Wl,--wrap,exit -Wl,--wrap,atexit -Wl,-n -Wl,--wrap,printf -Wl,--wrap,sprintf -Wl,--wrap,snprintf -Wl,--wrap,vprintf -Wl,--wrap,vsprintf -Wl,--wrap,vsnprintf -Wl,--wrap,fprintf -Wl,--wrap,vfprintf -mcpu=cortex-m4 -mthumb -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fmessage-length=0 -fno-exceptions -ffunction-sections -fdata-sections -funsigned-char -MMD -fomit-frame-pointer -Og -DMBED_DEBUG -DMBED_TRAP_ERRORS_ENABLED=1 -DMBED_MINIMAL_PRINTF -mcpu=cortex-m4 -mthumb -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -DMBED_ROM_START=0x8000000 -DMBED_ROM_SIZE=0x80000 -DMBED_RAM_START=0x20000000 -DMBED_RAM_SIZE=0x20000 -DMBED_BOOT_STACK_SIZE=4096 -DXIP_ENABLE=0


C_FLAGS += -c
C_FLAGS += -g3
C_FLAGS += -std=gnu11
C_FLAGS += -include
C_FLAGS += mbed_config.h
C_FLAGS += -DTARGET_CORTEX
C_FLAGS += -DTARGET_NAME=WEACT_F411CE
C_FLAGS += -DDEVICE_RESET_REASON=1
C_FLAGS += -DTARGET_LIKE_CORTEX_M4
C_FLAGS += -DTARGET_RELEASE
C_FLAGS += -DTOOLCHAIN_GCC_ARM
C_FLAGS += -DDEVICE_USBDEVICE=1
C_FLAGS += -DTARGET_WEACT_F411CE
C_FLAGS += -DARM_MATH_CM4
C_FLAGS += -DDEVICE_ANALOGIN=1
C_FLAGS += -DUSE_FULL_LL_DRIVER
C_FLAGS += -DDEVICE_WATCHDOG=1
C_FLAGS += -D__CMSIS_RTOS
C_FLAGS += -DTARGET_CORTEX_M
C_FLAGS += -D__MBED__=1
C_FLAGS += -DDEVICE_STDIO_MESSAGES=1
C_FLAGS += -DUSE_HAL_DRIVER
C_FLAGS += -DDEVICE_SERIAL=1
C_FLAGS += -DDEVICE_SERIAL_ASYNCH=1
C_FLAGS += -DDEVICE_SPI=1
C_FLAGS += -DDEVICE_MPU=1
C_FLAGS += -D__CORTEX_M4
C_FLAGS += -DDEVICE_SPI_ASYNCH=1
C_FLAGS += -DTARGET_M4
C_FLAGS += -DDEVICE_SPISLAVE=1
C_FLAGS += -DDEVICE_PORTIN=1
C_FLAGS += -DDEVICE_RTC=1
C_FLAGS += -DTOOLCHAIN_GCC
C_FLAGS += -D__FPU_PRESENT=1
C_FLAGS += -DTARGET_STM
C_FLAGS += -DTARGET_LIKE_MBED
C_FLAGS += -DDEVICE_SLEEP=1
C_FLAGS += -DSTM32F411xE
C_FLAGS += -DDEVICE_I2CSLAVE=1
C_FLAGS += -DTRANSACTION_QUEUE_SIZE_SPI=2
C_FLAGS += -DMBED_BUILD_TIMESTAMP=1594853718.8424242
C_FLAGS += -DCOMPONENT_SPIF=1
C_FLAGS += -DTARGET_RTOS_M4_M7
C_FLAGS += -D__MBED_CMSIS_RTOS_CM
C_FLAGS += -DDEVICE_I2C_ASYNCH=1
C_FLAGS += -DDEVICE_PORTOUT=1
C_FLAGS += -DDEVICE_FLASH=1
C_FLAGS += -DDEVICE_INTERRUPTIN=1
C_FLAGS += -DDEVICE_SERIAL_FC=1
C_FLAGS += -DDEVICE_USTICKER=1
C_FLAGS += -DDEVICE_I2C=1
C_FLAGS += -DCOMPONENT_FLASHIAP=1
C_FLAGS += -DDEVICE_PWMOUT=1
C_FLAGS += -DDEVICE_PORTINOUT=1
C_FLAGS += -DTARGET_MCU_STM32
C_FLAGS += -DTARGET_STM32F4
C_FLAGS += -DTARGET_STM32F411xE
C_FLAGS += -include
C_FLAGS += mbed_config.h
C_FLAGS += -c
C_FLAGS += -g3
C_FLAGS += -std=gnu11
C_FLAGS += -Wall
C_FLAGS += -Wextra
C_FLAGS += -Wno-unused-parameter
C_FLAGS += -Wno-missing-field-initializers
C_FLAGS += -fmessage-length=0
C_FLAGS += -fno-exceptions
C_FLAGS += -ffunction-sections
C_FLAGS += -fdata-sections
C_FLAGS += -funsigned-char
C_FLAGS += -MMD
C_FLAGS += -fomit-frame-pointer
C_FLAGS += -Og
C_FLAGS += -DMBED_DEBUG
C_FLAGS += -DMBED_TRAP_ERRORS_ENABLED=1
C_FLAGS += -DMBED_MINIMAL_PRINTF
C_FLAGS += -mcpu=cortex-m4
C_FLAGS += -mthumb
C_FLAGS += -mfpu=fpv4-sp-d16
C_FLAGS += -mfloat-abi=softfp
C_FLAGS += -DMBED_ROM_START=0x8000000
C_FLAGS += -DMBED_ROM_SIZE=0x80000
C_FLAGS += -DMBED_RAM_START=0x20000000
C_FLAGS += -DMBED_RAM_SIZE=0x20000

CXX_FLAGS += -c
CXX_FLAGS += -g3
CXX_FLAGS += -std=gnu++14
CXX_FLAGS += -fno-rtti
CXX_FLAGS += -Wvla
CXX_FLAGS += -include
CXX_FLAGS += mbed_config.h
CXX_FLAGS += -DTARGET_CORTEX
CXX_FLAGS += -DTARGET_NAME=WEACT_F411CE
CXX_FLAGS += -DDEVICE_RESET_REASON=1
CXX_FLAGS += -DTARGET_LIKE_CORTEX_M4
CXX_FLAGS += -DTARGET_RELEASE
CXX_FLAGS += -DTOOLCHAIN_GCC_ARM
CXX_FLAGS += -DDEVICE_USBDEVICE=1
CXX_FLAGS += -DTARGET_WEACT_F411CE
CXX_FLAGS += -DARM_MATH_CM4
CXX_FLAGS += -DDEVICE_ANALOGIN=1
CXX_FLAGS += -DUSE_FULL_LL_DRIVER
CXX_FLAGS += -DDEVICE_WATCHDOG=1
CXX_FLAGS += -D__CMSIS_RTOS
CXX_FLAGS += -DTARGET_CORTEX_M
CXX_FLAGS += -D__MBED__=1
CXX_FLAGS += -DDEVICE_STDIO_MESSAGES=1
CXX_FLAGS += -DUSE_HAL_DRIVER
CXX_FLAGS += -DDEVICE_SERIAL=1
CXX_FLAGS += -DDEVICE_SERIAL_ASYNCH=1
CXX_FLAGS += -DDEVICE_SPI=1
CXX_FLAGS += -DDEVICE_MPU=1
CXX_FLAGS += -D__CORTEX_M4
CXX_FLAGS += -DDEVICE_SPI_ASYNCH=1
CXX_FLAGS += -DTARGET_M4
CXX_FLAGS += -DDEVICE_SPISLAVE=1
CXX_FLAGS += -DDEVICE_PORTIN=1
CXX_FLAGS += -DDEVICE_RTC=1
CXX_FLAGS += -DTOOLCHAIN_GCC
CXX_FLAGS += -D__FPU_PRESENT=1
CXX_FLAGS += -DTARGET_STM
CXX_FLAGS += -DTARGET_LIKE_MBED
CXX_FLAGS += -DDEVICE_SLEEP=1
CXX_FLAGS += -DSTM32F411xE
CXX_FLAGS += -DDEVICE_I2CSLAVE=1
CXX_FLAGS += -DTRANSACTION_QUEUE_SIZE_SPI=2
CXX_FLAGS += -DMBED_BUILD_TIMESTAMP=1594853718.8424242
CXX_FLAGS += -DCOMPONENT_SPIF=1
CXX_FLAGS += -DTARGET_RTOS_M4_M7
CXX_FLAGS += -D__MBED_CMSIS_RTOS_CM
CXX_FLAGS += -DDEVICE_I2C_ASYNCH=1
CXX_FLAGS += -DDEVICE_PORTOUT=1
CXX_FLAGS += -DDEVICE_FLASH=1
CXX_FLAGS += -DDEVICE_INTERRUPTIN=1
CXX_FLAGS += -DDEVICE_SERIAL_FC=1
CXX_FLAGS += -DDEVICE_USTICKER=1
CXX_FLAGS += -DDEVICE_I2C=1
CXX_FLAGS += -DCOMPONENT_FLASHIAP=1
CXX_FLAGS += -DDEVICE_PWMOUT=1
CXX_FLAGS += -DDEVICE_PORTINOUT=1
CXX_FLAGS += -DTARGET_MCU_STM32
CXX_FLAGS += -DTARGET_STM32F4
CXX_FLAGS += -DTARGET_STM32F411xE
CXX_FLAGS += -include
CXX_FLAGS += mbed_config.h
CXX_FLAGS += -c
CXX_FLAGS += -g3
CXX_FLAGS += -std=gnu++14
CXX_FLAGS += -fno-rtti
CXX_FLAGS += -Wvla
CXX_FLAGS += -Wall
CXX_FLAGS += -Wextra
CXX_FLAGS += -Wno-unused-parameter
CXX_FLAGS += -Wno-missing-field-initializers
CXX_FLAGS += -fmessage-length=0
CXX_FLAGS += -fno-exceptions
CXX_FLAGS += -ffunction-sections
CXX_FLAGS += -fdata-sections
CXX_FLAGS += -funsigned-char
CXX_FLAGS += -MMD
CXX_FLAGS += -fomit-frame-pointer
CXX_FLAGS += -Og
CXX_FLAGS += -DMBED_DEBUG
CXX_FLAGS += -DMBED_TRAP_ERRORS_ENABLED=1
CXX_FLAGS += -DMBED_MINIMAL_PRINTF
CXX_FLAGS += -mcpu=cortex-m4
CXX_FLAGS += -mthumb
CXX_FLAGS += -mfpu=fpv4-sp-d16
CXX_FLAGS += -mfloat-abi=softfp
CXX_FLAGS += -DMBED_ROM_START=0x8000000
CXX_FLAGS += -DMBED_ROM_SIZE=0x80000
CXX_FLAGS += -DMBED_RAM_START=0x20000000
CXX_FLAGS += -DMBED_RAM_SIZE=0x20000

ASM_FLAGS += -c
ASM_FLAGS += -g3
ASM_FLAGS += -x
ASM_FLAGS += assembler-with-cpp
ASM_FLAGS += -D__FPU_PRESENT=1
ASM_FLAGS += -DUSE_HAL_DRIVER
ASM_FLAGS += -DSTM32F411xE
ASM_FLAGS += -DARM_MATH_CM4
ASM_FLAGS += -D__CORTEX_M4
ASM_FLAGS += -DTRANSACTION_QUEUE_SIZE_SPI=2
ASM_FLAGS += -DUSE_FULL_LL_DRIVER
ASM_FLAGS += -D__CMSIS_RTOS
ASM_FLAGS += -D__MBED_CMSIS_RTOS_CM
ASM_FLAGS += -I..
ASM_FLAGS += -I..\..\..\custom_targets\TARGET_STM\TARGET_STM32F4\TARGET_STM32F411xE\TARGET_WEACT_F411CE
ASM_FLAGS += -I..\..\..\libs
ASM_FLAGS += -I..\..\..\libs\Adafruit-GFX-Library
ASM_FLAGS += -I..\..\..\libs\Adafruit-GFX-Library\Fonts
ASM_FLAGS += -I..\..\..\libs\Adafruit_ADS1015
ASM_FLAGS += -I..\..\..\libs\Adafruit_ST7735
ASM_FLAGS += -I..\..\..\libs\Chart
ASM_FLAGS += -I..\..\..\libs\DHT
ASM_FLAGS += -I..\..\..\libs\IRSensorD6T
ASM_FLAGS += -I..\..\..\libs\Interfaces
ASM_FLAGS += -I..\..\..\libs\MCP23017
ASM_FLAGS += -I..\..\..\libs\MD_MAX72XX
ASM_FLAGS += -I..\..\..\libs\MD_MAX72XX\src
ASM_FLAGS += -I..\..\..\libs\MD_Parola
ASM_FLAGS += -I..\..\..\libs\MD_Parola\src
ASM_FLAGS += -I..\..\..\libs\MQTTPacket
ASM_FLAGS += -I..\..\..\libs\Math
ASM_FLAGS += -I..\..\..\libs\OneButton
ASM_FLAGS += -I..\..\..\libs\Radio
ASM_FLAGS += -I..\..\..\libs\Sensors
ASM_FLAGS += -I..\..\..\libs\TextLCD
ASM_FLAGS += -I..\..\..\libs\util
ASM_FLAGS += -I..\..\..\mbed-os
ASM_FLAGS += -I..\..\..\mbed-os\cmsis
ASM_FLAGS += -I..\..\..\mbed-os\cmsis\TARGET_CORTEX_M
ASM_FLAGS += -I..\..\..\mbed-os\components
ASM_FLAGS += -I..\..\..\mbed-os\components\802.15.4_RF
ASM_FLAGS += -I..\..\..\mbed-os\components\802.15.4_RF\atmel-rf-driver
ASM_FLAGS += -I..\..\..\mbed-os\components\802.15.4_RF\mcr20a-rf-driver
ASM_FLAGS += -I..\..\..\mbed-os\components\802.15.4_RF\stm-s2lp-rf-driver
ASM_FLAGS += -I..\..\..\mbed-os\components\storage\blockdevice\COMPONENT_FLASHIAP
ASM_FLAGS += -I..\..\..\mbed-os\components\storage\blockdevice\COMPONENT_SPIF
ASM_FLAGS += -I..\..\..\mbed-os\components\wifi
ASM_FLAGS += -I..\..\..\mbed-os\components\wifi\esp8266-driver
ASM_FLAGS += -I..\..\..\mbed-os\drivers
ASM_FLAGS += -I..\..\..\mbed-os\drivers\internal
ASM_FLAGS += -I..\..\..\mbed-os\events
ASM_FLAGS += -I..\..\..\mbed-os\events\internal
ASM_FLAGS += -I..\..\..\mbed-os\features
ASM_FLAGS += -I..\..\..\mbed-os\features\cellular
ASM_FLAGS += -I..\..\..\mbed-os\features\device_key
ASM_FLAGS += -I..\..\..\mbed-os\features\frameworks
ASM_FLAGS += -I..\..\..\mbed-os\features\frameworks\greentea-client
ASM_FLAGS += -I..\..\..\mbed-os\features\frameworks\mbed-client-cli
ASM_FLAGS += -I..\..\..\mbed-os\features\frameworks\mbed-client-randlib
ASM_FLAGS += -I..\..\..\mbed-os\features\frameworks\mbed-coap
ASM_FLAGS += -I..\..\..\mbed-os\features\frameworks\mbed-trace
ASM_FLAGS += -I..\..\..\mbed-os\features\frameworks\mbed-trace\mbed-trace
ASM_FLAGS += -I..\..\..\mbed-os\features\frameworks\nanostack-libservice
ASM_FLAGS += -I..\..\..\mbed-os\features\frameworks\unity
ASM_FLAGS += -I..\..\..\mbed-os\features\frameworks\utest
ASM_FLAGS += -I..\..\..\mbed-os\features\lorawan
ASM_FLAGS += -I..\..\..\mbed-os\features\lwipstack
ASM_FLAGS += -I..\..\..\mbed-os\features\mbedtls
ASM_FLAGS += -I..\..\..\mbed-os\features\nanostack
ASM_FLAGS += -I..\..\..\mbed-os\features\nanostack\coap-service
ASM_FLAGS += -I..\..\..\mbed-os\features\nanostack\mbed-mesh-api
ASM_FLAGS += -I..\..\..\mbed-os\features\nanostack\nanostack-hal-mbed-cmsis-rtos
ASM_FLAGS += -I..\..\..\mbed-os\features\nanostack\nanostack-interface
ASM_FLAGS += -I..\..\..\mbed-os\features\nanostack\sal-stack-nanostack
ASM_FLAGS += -I..\..\..\mbed-os\features\nanostack\sal-stack-nanostack-eventloop
ASM_FLAGS += -I..\..\..\mbed-os\features\netsocket
ASM_FLAGS += -I..\..\..\mbed-os\features\storage
ASM_FLAGS += -I..\..\..\mbed-os\features\storage\blockdevice
ASM_FLAGS += -I..\..\..\mbed-os\features\storage\filesystem
ASM_FLAGS += -I..\..\..\mbed-os\features\storage\filesystem\fat
ASM_FLAGS += -I..\..\..\mbed-os\features\storage\filesystem\fat\ChaN
ASM_FLAGS += -I..\..\..\mbed-os\features\storage\filesystem\littlefs
ASM_FLAGS += -I..\..\..\mbed-os\features\storage\filesystem\littlefsv2
ASM_FLAGS += -I..\..\..\mbed-os\features\storage\filesystem\littlefsv2\littlefs
ASM_FLAGS += -I..\..\..\mbed-os\features\storage\kvstore
ASM_FLAGS += -I..\..\..\mbed-os\features\storage\kvstore\conf
ASM_FLAGS += -I..\..\..\mbed-os\features\storage\kvstore\direct_access_devicekey
ASM_FLAGS += -I..\..\..\mbed-os\features\storage\kvstore\filesystemstore
ASM_FLAGS += -I..\..\..\mbed-os\features\storage\kvstore\global_api
ASM_FLAGS += -I..\..\..\mbed-os\features\storage\kvstore\include
ASM_FLAGS += -I..\..\..\mbed-os\features\storage\kvstore\kv_map
ASM_FLAGS += -I..\..\..\mbed-os\features\storage\kvstore\securestore
ASM_FLAGS += -I..\..\..\mbed-os\features\storage\kvstore\tdbstore
ASM_FLAGS += -I..\..\..\mbed-os\hal
ASM_FLAGS += -I..\..\..\mbed-os\hal\usb
ASM_FLAGS += -I..\..\..\mbed-os\platform
ASM_FLAGS += -I..\..\..\mbed-os\platform\cxxsupport
ASM_FLAGS += -I..\..\..\mbed-os\platform\internal
ASM_FLAGS += -I..\..\..\mbed-os\platform\source
ASM_FLAGS += -I..\..\..\mbed-os\platform\source\minimal-printf
ASM_FLAGS += -I..\..\..\mbed-os\rtos
ASM_FLAGS += -I..\..\..\mbed-os\rtos\source
ASM_FLAGS += -I..\..\..\mbed-os\rtos\source\TARGET_CORTEX
ASM_FLAGS += -I..\..\..\mbed-os\targets\TARGET_STM
ASM_FLAGS += -I..\..\..\mbed-os\targets\TARGET_STM\TARGET_STM32F4
ASM_FLAGS += -I..\..\..\mbed-os\targets\TARGET_STM\TARGET_STM32F4\STM32Cube_FW
ASM_FLAGS += -I..\..\..\mbed-os\targets\TARGET_STM\TARGET_STM32F4\STM32Cube_FW\CMSIS
ASM_FLAGS += -I..\..\..\mbed-os\targets\TARGET_STM\TARGET_STM32F4\STM32Cube_FW\STM32F4xx_HAL_Driver
ASM_FLAGS += -I..\..\..\mbed-os\targets\TARGET_STM\TARGET_STM32F4\STM32Cube_FW\STM32F4xx_HAL_Driver\Legacy
ASM_FLAGS += -I..\..\..\mbed-os\targets\TARGET_STM\TARGET_STM32F4\TARGET_STM32F411xE
ASM_FLAGS += -I..\source
ASM_FLAGS += -ID:\Projects\Sn\LocalGit\Mbed5-Projects\mbed-os
ASM_FLAGS += -include
ASM_FLAGS += .\mbed_config.h
ASM_FLAGS += -c
ASM_FLAGS += -g3
ASM_FLAGS += -x
ASM_FLAGS += assembler-with-cpp
ASM_FLAGS += -Wall
ASM_FLAGS += -Wextra
ASM_FLAGS += -Wno-unused-parameter
ASM_FLAGS += -Wno-missing-field-initializers
ASM_FLAGS += -fmessage-length=0
ASM_FLAGS += -fno-exceptions
ASM_FLAGS += -ffunction-sections
ASM_FLAGS += -fdata-sections
ASM_FLAGS += -funsigned-char
ASM_FLAGS += -MMD
ASM_FLAGS += -fomit-frame-pointer
ASM_FLAGS += -Og
ASM_FLAGS += -DMBED_DEBUG
ASM_FLAGS += -DMBED_TRAP_ERRORS_ENABLED=1
ASM_FLAGS += -DMBED_MINIMAL_PRINTF
ASM_FLAGS += -mcpu=cortex-m4
ASM_FLAGS += -mthumb
ASM_FLAGS += -mfpu=fpv4-sp-d16
ASM_FLAGS += -mfloat-abi=softfp


LD_FLAGS :=-Wl,--gc-sections -Wl,--wrap,main -Wl,--wrap,_malloc_r -Wl,--wrap,_free_r -Wl,--wrap,_realloc_r -Wl,--wrap,_memalign_r -Wl,--wrap,_calloc_r -Wl,--wrap,exit -Wl,--wrap,atexit -Wl,-n -Wl,--wrap,printf -Wl,--wrap,sprintf -Wl,--wrap,snprintf -Wl,--wrap,vprintf -Wl,--wrap,vsprintf -Wl,--wrap,vsnprintf -Wl,--wrap,fprintf -Wl,--wrap,vfprintf -mcpu=cortex-m4 -mthumb -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -DMBED_ROM_START=0x8000000 -DMBED_ROM_SIZE=0x80000 -DMBED_RAM_START=0x20000000 -DMBED_RAM_SIZE=0x20000 -DMBED_BOOT_STACK_SIZE=4096 -DXIP_ENABLE=0 
LD_SYS_LIBS :=-Wl,--start-group -lstdc++ -lsupc++ -lm -lc -lgcc -lnosys  -Wl,--end-group

# Tools and Flags
###############################################################################
# Rules

.PHONY: all lst size


all: $(PROJECT).bin $(PROJECT).hex size


.s.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Assemble: $(notdir $<)"
  
	@$(AS) -c $(ASM_FLAGS) -o $@ $<
  


.S.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Assemble: $(notdir $<)"
  
	@$(AS) -c $(ASM_FLAGS) -o $@ $<
  

.c.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Compile: $(notdir $<)"
	@$(CC) $(C_FLAGS) $(INCLUDE_PATHS) -o $@ $<

.cpp.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Compile: $(notdir $<)"
	@$(CPP) $(CXX_FLAGS) $(INCLUDE_PATHS) -o $@ $<


$(PROJECT).link_script.ld: $(LINKER_SCRIPT)
	@$(PREPROC) $< -o $@



$(PROJECT).elf: $(OBJECTS) $(SYS_OBJECTS) $(PROJECT).link_script.ld 
	+@echo "$(filter %.o, $^)" > .link_options.txt
	+@echo "link: $(notdir $@)"
	@$(LD) $(LD_FLAGS) -T $(filter-out %.o, $^) $(LIBRARY_PATHS) --output $@ @.link_options.txt $(LIBRARIES) $(LD_SYS_LIBS)


$(PROJECT).bin: $(PROJECT).elf
	$(ELF2BIN) -O binary $< $@
	+@echo "===== bin file ready to flash: $(OBJDIR)/$@ =====" 

$(PROJECT).hex: $(PROJECT).elf
	$(ELF2BIN) -O ihex $< $@


# Rules
###############################################################################
# Dependencies

DEPS = $(OBJECTS:.o=.d) $(SYS_OBJECTS:.o=.d)
-include $(DEPS)
endif

# Dependencies
###############################################################################
# Catch-all

%: ;

# Catch-all
###############################################################################
